### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by ajbeach2** [GetStream/Stream-Example-Py#11]
I am using python 2.7.11 with pyenv

I ran pip install -r requirements.txt, everything built/installed fine however, when I run

```bash
./manage.py migrate
```

I get the following stacktrace:
```bash
➜  Stream-Example-Py git:(master) ✗ ./manage.py migrate                                                                                                                                                                                        Thu Apr  7 11:21:29 CDT 2016
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/core/management/__init__.py", line 77, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 23, in <module>
    mod = import_module(app)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stream_django/__init__.py", line 1, in <module>
    from stream_django.feed_manager import feed_manager
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stream_django/feed_manager.py", line 7, in <module>
    feed_manager_class = get_class_from_string(FEED_MANAGER_CLASS)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stream_django/utils.py", line 14, in get_class_from_string
    mod = import_module(module)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stream_django/managers.py", line 4, in <module>
    from stream_django.client import stream_client
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stream_django/client.py", line 10, in <module>
    stream_client = stream.connect()
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stream/__init__.py", line 35, in connect
    return StreamClient(api_key, api_secret, app_id, version, timeout, location=location)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stream/client.py", line 67, in __init__
    self.auth = HTTPSignatureAuth(api_key, secret=api_secret)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/httpsig/requests_auth.py", line 25, in __init__
    algorithm=algorithm, headers=headers)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/httpsig/sign.py", line 85, in __init__
    super(HeaderSigner, self).__init__(secret=secret, algorithm=algorithm)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/httpsig/sign.py", line 41, in __init__
    self._hash = HMAC.new(secret, digestmod=HASHES[self.hash_algorithm])
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/Crypto/Hash/HMAC.py", line 211, in new
    return HMAC(key, msg, digestmod)
  File "/Users/alex.beach/.pyenv/versions/2.7.11/lib/python2.7/site-packages/Crypto/Hash/HMAC.py", line 122, in __init__
    if len(key) > blocksize:
TypeError: object of type 'NoneType' has no len()
```

**Comment by ajbeach2** [comment]
nvm i didn't read the install file :(
