### ISSUE TITLE
try without heroku?

### ISSUE THREAD

**Issue by pcompassion** [GetStream/Stream-Example-Py#7]
because I have no experience with heroku.

can I try the example on local machine?

 6. initialize your app ``` ./setup-heroku.sh ``

**Comment by tbarbugli** [comment]
sure, make sure to adjust your database settings and then run python manage.py after_deploy

**Comment by pcompassion** [comment]
Thanks

**Comment by anunayasri** [comment]
Hi, I am trying to setup Stream-Example-Py on my local machine. This is the first time I am working on a Django application, so I don't have much knowledge about what configurations to do. I am following the instructions given in -
https://github.com/GetStream/Stream-Example-Py/blob/master/install
I have installed rest of the dependencies but I am unable to find ./setup-heroku.sh in the project repository. Where is it located ? Secondly, don't I need to install redis or casandra or memcache on my local machine and give the configurations in django setttings.py to make the application work ?

**Comment by tbarbugli** [comment]
@anunayasri doc referred to an old script, you should use this to prepare your app
```python manage.py after_deploy ```

**Comment by anunayasri** [comment]
Do you have a new setup guide for the app ? What about database configurations ?

When I ran `python manage.py after_deploy`, I got the following error
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 77, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/anunaya/shopo/Stream-Framework/Stream-Example-Py/core/management/commands/after_deploy.py", line 3, in <module>
    from django.contrib.auth import get_user_model
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 5, in <module>
    from django.middleware.csrf import rotate_token
  File "/usr/local/lib/python2.7/site-packages/django/middleware/csrf.py", line 16, in <module>
    from django.utils.cache import patch_vary_headers
  File "/usr/local/lib/python2.7/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import get_cache
  File "/usr/local/lib/python2.7/site-packages/django/core/cache/__init__.py", line 143, in <module>
    cache = get_cache(DEFAULT_CACHE_ALIAS)
  File "/usr/local/lib/python2.7/site-packages/django/core/cache/__init__.py", line 130, in get_cache
    mod = importlib.import_module(mod_path)
  File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/django_pylibmc/memcached.py", line 25, in <module>
    raise InvalidCacheBackendError('Could not import pylibmc.')
django.core.cache.backends.base.InvalidCacheBackendError: Could not import pylibmc.
```

**Comment by tbarbugli** [comment]
did you run ```pip install -r requirements.txt```? the errors is about a missing dependency

**Comment by anunayasri** [comment]
Yes. It runs without any errors and says that the requirements are already satisfied.
The error was because my system library path was not correct. Its resolved now. But, as I feared, I am getting errors for database configuration. Here is the traceback:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 77, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/__init__.py", line 13, in <module>
    from south.management.commands.syncdb import Command as SyncCommand
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 19, in <module>
    from south.db import dbs
  File "/usr/local/lib/python2.7/site-packages/south/db/__init__.py", line 84, in <module>
    db = dbs[DEFAULT_DB_ALIAS]
KeyError: 'default'

```

**Comment by JelteF** [comment]
I updated the install.md file and it should be clear what to change now.
